name: ClickHouse Data Sync

on:
  # Запуск по расписанию (каждый день в 2:00 UTC)
  schedule:
    - cron: '0 2 * * *'
  
  # Ручной запуск
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        default: 'sync'
        type: choice
        options:
          - sync
          - create_table
          - test_connection
          - verify_data

jobs:
  clickhouse-sync:
    runs-on: ubuntu-latest
    
    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Yandex Cloud SSL certificates
        run: |
          echo "Installing Yandex Cloud SSL certificates..."
          sudo mkdir -p /usr/local/share/ca-certificates/Yandex
          sudo wget "https://storage.yandexcloud.net/cloud-certs/RootCA.pem" \
            -O /usr/local/share/ca-certificates/Yandex/RootCA.crt
          sudo wget "https://storage.yandexcloud.net/cloud-certs/IntermediateCA.pem" \
            -O /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt
          sudo chmod 644 /usr/local/share/ca-certificates/Yandex/RootCA.crt
          sudo chmod 644 /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt
          sudo update-ca-certificates
          echo "✅ SSL certificates installed successfully"
      
      - name: Test ClickHouse connection
        run: |
          echo "Testing ClickHouse connection..."
          curl -s --fail \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT 1" || {
            echo "❌ ClickHouse connection failed"
            exit 1
          }
          echo "✅ ClickHouse connection successful"
      
      - name: Create database
        if: github.event.inputs.operation == 'create_table' || github.event.inputs.operation == 'sync'
        run: |
          echo "Creating database..."
          curl -s --fail \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data-binary @data/raw/sql/create_database.sql || {
            echo "❌ Failed to create database"
            exit 1
          }
          echo "✅ Database created successfully"
      
      - name: Create table
        if: github.event.inputs.operation == 'create_table' || github.event.inputs.operation == 'sync'
        run: |
          echo "Creating table..."
          curl -s --fail \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data-binary @data/raw/sql/create_tables.sql || {
            echo "❌ Failed to create table"
            exit 1
          }
          echo "✅ Table created successfully"
      
      - name: Test S3 connection
        if: github.event.inputs.operation == 'sync' || github.event.inputs.operation == ''
        run: |
          echo "Testing S3 connection..."
          # Подстановка переменных в простой тестовый SQL файл
          sed "s/{ACCESS_KEY_ID}/${{ secrets.ACCESS_KEY_ID }}/g; s/{ACCESS_KEY_SECRET}/${{ secrets.ACCESS_KEY_SECRET }}/g" data/raw/sql/test_s3_simple.sql > temp_s3_test.sql
          
          echo "📋 Generated S3 test query:"
          cat temp_s3_test.sql
          
          echo "🔍 Testing S3 access..."
          response=$(curl -s -w "%{http_code}" \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data-binary @temp_s3_test.sql \
            --output s3_test_result.txt)
          
          echo "HTTP Status: $response"
          echo "Response:"
          cat s3_test_result.txt
          
          if [ "$response" -eq 200 ]; then
            echo "✅ S3 connection test successful"
          else
            echo "❌ S3 connection test failed"
            rm -f temp_s3_test.sql s3_test_result.txt
            exit 1
          fi
          
          rm -f temp_s3_test.sql s3_test_result.txt
      
      - name: Sync data from S3
        if: github.event.inputs.operation == 'sync' || github.event.inputs.operation == ''
        run: |
          echo "Syncing data from S3..."
          # Подстановка переменных в SQL файл
          sed "s/{ACCESS_KEY_ID}/${{ secrets.ACCESS_KEY_ID }}/g; s/{ACCESS_KEY_SECRET}/${{ secrets.ACCESS_KEY_SECRET }}/g" data/raw/sql/insert_data.sql > temp_insert.sql
          
          echo "📋 Generated INSERT query (first 20 lines):"
          head -20 temp_insert.sql
          
          echo "🔍 Executing INSERT query..."
          response=$(curl -s -w "%{http_code}" \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data-binary @temp_insert.sql \
            --output insert_result.txt)
          
          echo "HTTP Status: $response"
          echo "Response:"
          cat insert_result.txt
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Data synced successfully"
          else
            echo "❌ Failed to sync data"
            rm -f temp_insert.sql insert_result.txt
            exit 1
          fi
          
          rm -f temp_insert.sql insert_result.txt
      
      - name: Test data extraction
        if: github.event.inputs.operation == 'test_connection' || github.event.inputs.operation == 'verify_data'
        run: |
          echo "Testing data extraction..."
          # Подстановка переменных в SQL файл
          sed "s/{ACCESS_KEY_ID}/${{ secrets.ACCESS_KEY_ID }}/g; s/{ACCESS_KEY_SECRET}/${{ secrets.ACCESS_KEY_SECRET }}/g" data/raw/sql/test_queries.sql > temp_test.sql
          curl -s --fail \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data-binary @temp_test.sql || {
            echo "❌ Failed to test data extraction"
            exit 1
          }
          rm -f temp_test.sql
          echo "✅ Data extraction test successful"
      
      - name: Verify all fields
        if: github.event.inputs.operation == 'verify_data'
        run: |
          echo "Verifying all fields extraction..."
          # Подстановка переменных в SQL файл
          sed "s/{ACCESS_KEY_ID}/${{ secrets.ACCESS_KEY_ID }}/g; s/{ACCESS_KEY_SECRET}/${{ secrets.ACCESS_KEY_SECRET }}/g" data/raw/sql/verify_fields.sql > temp_verify.sql
          curl -s --fail \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data-binary @temp_verify.sql || {
            echo "❌ Failed to verify fields"
            exit 1
          }
          rm -f temp_verify.sql
          echo "✅ All fields verified successfully"
      
      - name: Get data statistics
        if: github.event.inputs.operation == 'sync' || github.event.inputs.operation == ''
        run: |
          echo "Getting data statistics..."
          curl -s \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT COUNT(*) as total_records, COUNT(DISTINCT match_id) as unique_matches, COUNT(DISTINCT team_id) as unique_teams FROM raw.match_stats" \
            --output stats.txt
          echo "📊 Data Statistics:"
          cat stats.txt