name: ML Training Dataset - Simple

on:
  # Запуск по расписанию (каждый день в 3:00 UTC, после sync raw данных)
  schedule:
    - cron: '0 3 * * *'
  
  # Ручной запуск
  workflow_dispatch:
    inputs:
      operation:
        description: 'Operation to perform'
        required: true
        default: 'build'
        type: choice
        options:
          - build           # Создать обучающую выборку
          - verify          # Проверить существующие данные
          - cleanup         # Очистить данные
  
  # Запуск после успешного завершения raw data sync
  workflow_run:
    workflows: ["ClickHouse Data Sync"]
    types:
      - completed

jobs:
  ml-training-dataset:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Yandex Cloud SSL certificates
        run: |
          echo "🔧 Installing Yandex Cloud SSL certificates..."
          sudo mkdir -p /usr/local/share/ca-certificates/Yandex
          sudo wget "https://storage.yandexcloud.net/cloud-certs/RootCA.pem" \
            -O /usr/local/share/ca-certificates/Yandex/RootCA.crt
          sudo wget "https://storage.yandexcloud.net/cloud-certs/IntermediateCA.pem" \
            -O /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt
          sudo chmod 644 /usr/local/share/ca-certificates/Yandex/RootCA.crt
          sudo chmod 644 /usr/local/share/ca-certificates/Yandex/IntermediateCA.crt
          sudo update-ca-certificates
          echo "✅ SSL certificates installed"
      
      - name: Test ClickHouse connection
        run: |
          echo "🔍 Testing ClickHouse connection..."
          curl -s --fail \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT 1" || {
            echo "❌ ClickHouse connection failed"
            exit 1
          }
          echo "✅ ClickHouse connection successful"
      
      - name: Verify raw data
        if: github.event.inputs.operation == 'build' || github.event.inputs.operation == '' || github.event.inputs.operation == 'verify'
        run: |
          echo "🔍 Checking raw data availability..."
          
          response=$(curl -s -w "%{http_code}" \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT COUNT(*) as total, COUNT(DISTINCT match_id) as matches FROM raw.match_stats" \
            --output raw_stats.txt)
          
          echo "📊 Raw data stats:"
          cat raw_stats.txt
          
          if [ "$response" -ne 200 ]; then
            echo "❌ Cannot access raw data"
            exit 1
          fi
          
          echo "✅ Raw data verification completed"
          rm -f raw_stats.txt
      
      - name: Build training dataset
        if: github.event.inputs.operation == 'build' || github.event.inputs.operation == ''
        run: |
          echo "🚀 Building training dataset with ClickHouse window functions..."
          echo "This creates ml.training_dataset table with features and targets"
          
          response=$(curl -s -w "%{http_code}" \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data-binary @data/ml/sql/build_training_dataset.sql \
            --output build_result.txt)
          
          echo "HTTP Status: $response"
          echo "Response:"
          head -20 build_result.txt
          
          if [ "$response" -eq 200 ]; then
            echo "✅ Training dataset built successfully"
          else
            echo "❌ Failed to build training dataset"
            echo "Full error:"
            cat build_result.txt
            rm -f build_result.txt
            exit 1
          fi
          
          rm -f build_result.txt
      
      - name: Verify dataset quality
        if: github.event.inputs.operation == 'build' || github.event.inputs.operation == '' || github.event.inputs.operation == 'verify'
        run: |
          echo "🔍 Verifying training dataset quality..."
          
          # Базовая статистика
          echo "📊 Basic Statistics:"
          curl -s \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT 
              COUNT(*) as total_records,
              COUNT(DISTINCT match_id) as unique_matches,
              COUNT(DISTINCT home_team_id) as home_teams,
              COUNT(DISTINCT away_team_id) as away_teams,
              MIN(match_date) as earliest_date,
              MAX(match_date) as latest_date
            FROM ml.training_dataset FORMAT Vertical"
          
          echo ""
          echo "🎯 Target Distribution:"
          curl -s \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT 
              'match_result' as target,
              target_match_result as value,
              COUNT(*) as count,
              ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM ml.training_dataset), 1) as percentage
            FROM ml.training_dataset 
            GROUP BY target_match_result 
            ORDER BY target_match_result FORMAT PrettyCompact"
          
          echo ""
          echo "⚽ Goals Totals:"
          curl -s \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT 
              ROUND(AVG(target_total_goals_over_1_5) * 100, 1) as pct_over_1_5,
              ROUND(AVG(target_total_goals_over_2_5) * 100, 1) as pct_over_2_5,
              ROUND(AVG(target_total_goals_over_3_5) * 100, 1) as pct_over_3_5
            FROM ml.training_dataset FORMAT Vertical"
          
          echo ""
          echo "📈 Feature Quality Check:"
          curl -s \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT 
              countIf(home_goals_avg_7 IS NULL) as null_home_goals,
              countIf(away_goals_avg_7 IS NULL) as null_away_goals,
              countIf(home_goals_avg_7 < 0) as negative_home_goals,
              countIf(away_goals_avg_7 < 0) as negative_away_goals,
              ROUND(AVG(home_goals_avg_7), 2) as avg_home_goals_7,
              ROUND(AVG(away_goals_avg_7), 2) as avg_away_goals_7
            FROM ml.training_dataset FORMAT Vertical"
          
          echo "✅ Dataset quality verification completed"
      
      - name: Cleanup ML data
        if: github.event.inputs.operation == 'cleanup'
        run: |
          echo "🗑️  Cleaning up ML training dataset..."
          
          curl -s \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "DROP TABLE IF EXISTS ml.training_dataset"
          
          echo "✅ ML training dataset cleaned up"
      
      - name: Success summary
        if: success() && (github.event.inputs.operation == 'build' || github.event.inputs.operation == '')
        run: |
          echo "🎉 ML Training Dataset Generation completed successfully!"
          echo ""
          echo "📊 Quick Stats:"
          curl -s \
            "https://${{ secrets.CLICKHOUSE_HOST }}:8443/" \
            --user "${{ secrets.CLICKHOUSE_USER }}:${{ secrets.CLICKHOUSE_PASSWORD }}" \
            --data "SELECT 
              COUNT(*) as records,
              COUNT(DISTINCT match_id) as matches,
              ROUND(AVG(target_total_goals_over_2_5) * 100, 1) as pct_over_2_5_goals
            FROM ml.training_dataset"
          echo ""
          echo "🔗 Dataset ready at: ml.training_dataset"
          echo "📝 Use SQL queries to explore and export data for ML models"